#############################################################################
# Makefile for building: homework1109
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  homework1109\homework1109.pro
# Template: app
# Command: F:\QT5.6.3x86\5.6.3\msvc2013\bin\qmake.exe -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile homework1109\homework1109.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = F:\QT5.6.3x86\5.6.3\msvc2013\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: homework1109\homework1109.pro F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\win32-msvc2013\qmake.conf F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\spec_pre.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\common\angle.conf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\common\msvc-base.conf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\common\msvc-desktop.conf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\qconfig.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dcore.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dinput.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquick.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickinput.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickrender.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3drender.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3drender_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axbase.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axserver.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_concurrent.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_core.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_core_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_dbus.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_designer.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_designer_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_gui.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_gui_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_help.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_help_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_labscontrols_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_labstemplates_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_location.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_location_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimedia.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_network.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_network_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_nfc.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_opengl.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_positioning.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_printsupport.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qml.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qml_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qmltest.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quick.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quick_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_script.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_script_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_scripttools.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sensors.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialbus.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialbus_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialport.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sql.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sql_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_svg.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_svg_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_testlib.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_uitools.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webchannel.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webengine.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_websockets.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webview.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webview_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_widgets.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_winextras.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xml.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xml_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_zlib_private.pri \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qt_functions.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qt_config.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\qt_config.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\win32-msvc2013\qmake.conf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\spec_post.prf \
		.qmake.stash \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\exclusive_builds.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\default_pre.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\default_pre.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\resolve_config.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\exclusive_builds_post.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\default_post.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\console.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qml_debug.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\rtti.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\precompile_header.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\warn_on.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qt.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\resources.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\moc.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\file_copies.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\testcase_targets.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\exceptions.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\yacc.prf \
		F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\lex.prf \
		homework1109\homework1109.pro \
		F:\QT5.6.3x86\5.6.3\msvc2013\lib\Qt5Core.prl
	$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile homework1109\homework1109.pro
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\spec_pre.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\common\angle.conf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\common\msvc-base.conf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\common\msvc-desktop.conf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\qconfig.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dcore.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dinput.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquick.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickinput.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickinput_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickrender.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3dquickrender_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3drender.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_3drender_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axbase.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axserver.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_concurrent.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_core.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_core_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_dbus.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_designer.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_designer_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_gui.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_gui_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_help.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_help_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_labscontrols_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_labstemplates_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_location.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_location_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimedia.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_network.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_network_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_nfc.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_opengl.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_positioning.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_printsupport.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qml.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qml_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qmltest.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quick.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quick_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_script.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_script_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_scripttools.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sensors.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialbus.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialbus_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialport.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sql.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_sql_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_svg.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_svg_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_testlib.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_uitools.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webchannel.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webengine.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_websockets.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webview.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_webview_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_widgets.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_winextras.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xml.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xml_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\modules\qt_lib_zlib_private.pri:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qt_functions.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qt_config.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\qt_config.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\win32-msvc2013\qmake.conf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\spec_post.prf:
.qmake.stash:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\exclusive_builds.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\default_pre.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\default_pre.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\resolve_config.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\exclusive_builds_post.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\default_post.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\console.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qml_debug.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\win32\rtti.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\precompile_header.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\warn_on.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\qt.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\resources.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\moc.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\file_copies.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\testcase_targets.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\exceptions.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\yacc.prf:
F:\QT5.6.3x86\5.6.3\msvc2013\mkspecs\features\lex.prf:
homework1109\homework1109.pro:
F:\QT5.6.3x86\5.6.3\msvc2013\lib\Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile homework1109\homework1109.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) homework1109.exp
	-$(DEL_FILE) homework1109.vc.pdb
	-$(DEL_FILE) homework1109.ilk
	-$(DEL_FILE) homework1109.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash homework1109.lib homework1109.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
